openapi: 3.0.0
info:
  title: TD Ameritrade API - OAuth2
  description: This is replication of the TD Ameritrade API.
  version: 0.1.3
servers:
- url: https://api.tdameritrade.com/v1
security:
- application:
  - read
  - write
paths:
  /oauth2/token:
    post:
      tags:
      - Authentication
      summary: Post Access Token
      description: The token endpoint returns an access token along with an optional
        refresh token.
      operationId: oauth2TokenPOST
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostAccessBody'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EASObject'
      security: []
      x-swagger-router-controller: Authentication
  /accounts/{accountId}/orders/{orderId}:
    delete:
      tags:
      - Accounts and Trading
      - Orders
      summary: Cancel Order
      description: Cancel a specific order for a spcific account
      operationId: accountsAccountIdOrdersOrderIdDELETE
      parameters:
      - name: accountId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: orderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EASObject'
      security:
      - bearerAuth: []
      x-swagger-router-controller: AccountsAndTrading
  /marketdata/{symbol}/pricehistory:
    get:
      tags:
      - Price History
      summary: Get price history for a symbol
      operationId: marketdataSymbolPricehistoryGET
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: apikey
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: periodType
        in: query
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/PeriodType'
      - name: period
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: frequencyType
        in: query
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/FrequencyType'
      - name: frequency
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: endDate
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: startDate
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: needExtendedHoursData
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandleList'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      security:
      - bearerAuth: []
      x-swagger-router-controller: PriceHistory
  /instruments:
    get:
      tags:
      - Search Instruments
      summary: Search or retrieve instrument data, including fundamental data
      operationId: instrumentsGET
      parameters:
      - name: apikey
        in: query
        description: Pass your OAuth User ID to make an unauthenticated request for
          delayed data.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: symbol
        in: query
        description: Value to pass to the search. See projection description for more
          information.
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: projection
        in: query
        description: 'The type of request: symbol-search: Retrieve instrument data
          of a specific symbol or cusip symbol-regex: Retrieve instrument data for
          all symbols matching regex. Example: symbol=XYZ.* will return all symbols
          beginning with XYZ desc-search: Retrieve instrument data for instruments
          whose description contains the word supplied. Example: symbol=FakeCompany
          will return all instruments with FakeCompany in the description. desc-regex:
          Search description with full regex support. Example: symbol=XYZ.[A-C] returns
          all instruments whose descriptions contain a word beginning with XYZ followed
          by a character A through C. fundamental: Returns fundamental data for a
          single instrument specified by exact symbol.'
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                Instrument:
                  $ref: '#/components/examples/instrumentObject'
                Fundamental:
                  $ref: '#/components/examples/fundamentalObject'
                FundamentalData:
                  $ref: '#/components/examples/fundamentalDataObject'
                Bond:
                  $ref: '#/components/examples/bondObject'
        "400":
          description: An error message indicating the caller must pass a non null
            value in the parameter.
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: An error message indicating the instrument for the symbol/cusip
            was not found.
        "406":
          description: An error message indicating an issue in the symbol regex, or
            number of symbols searched is over the maximum.
      security:
      - bearerAuth: []
      x-swagger-router-controller: SearchInstruments
components:
  schemas:
    FrequencyType:
      type: string
      enum:
      - minute
      - daily
      - weekly
      - monthly
    PeriodType:
      type: string
      enum:
      - day
      - month
      - year
      - ytd
    PostAccessBody:
      required:
      - client_id
      - grant_type
      type: object
      properties:
        grant_type:
          type: string
          description: The grant type of the oAuth scheme. Possible values are authorization_code,
            refresh_token
        refresh_token:
          type: string
          description: Required if using refresh token grant
        access_type:
          type: string
          description: Set to offline to receive a refresh token on an authorization_code
            grant type request. Do not set to offline on a refresh_token grant type
            request.
        code:
          type: string
          description: Required if trying to use authorization code grant
        client_id:
          type: integer
          description: OAuth User ID of your application
        redirect_uri:
          type: string
          description: Required if trying to use authorization code grant
      description: Body Parmeers for the Post Access Token Endpoint
    CandleList:
      type: object
      properties:
        candles:
          type: array
          items:
            $ref: '#/components/schemas/CandleList_candles'
        empty:
          type: boolean
        symbol:
          type: string
          description: Symbol
      description: List of Candles
      example:
        symbol: symbol
        candles:
        - volume: 2.3021358869347654518833223846741020679473876953125
          datetime: 6
          high: 1.46581298050294517310021547018550336360931396484375
          low: 5.962133916683182377482808078639209270477294921875
          close: 0.80082819046101150206595775671303272247314453125
          open: 5.63737665663332876420099637471139430999755859375
        - volume: 2.3021358869347654518833223846741020679473876953125
          datetime: 6
          high: 1.46581298050294517310021547018550336360931396484375
          low: 5.962133916683182377482808078639209270477294921875
          close: 0.80082819046101150206595775671303272247314453125
          open: 5.63737665663332876420099637471139430999755859375
        empty: true
    EASObject:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
          format: int32
        scope:
          type: string
        refresh_token_expires_in:
          type: integer
          format: int32
      example:
        access_token: access_token
        refresh_token_expires_in: 6
        refresh_token: refresh_token
        scope: scope
        token_type: token_type
        expires_in: 0
    Bond:
      type: object
      properties:
        bondPrice:
          type: number
          format: double
        cusip:
          type: string
        symbol:
          type: string
        description:
          type: string
        exchange:
          type: string
        assetType:
          type: string
          enum:
          - BOND
    FundamentalData:
      type: object
      properties:
        symbol:
          type: string
        high52:
          type: number
          format: double
        low52:
          type: number
          format: double
        dividendAmount:
          type: number
          format: double
        dividendYield:
          type: number
          format: double
        dividendDate:
          type: string
        peRatio:
          type: number
          format: double
        pegRatio:
          type: number
          format: double
        pbRatio:
          type: number
          format: double
        prRatio:
          type: number
          format: double
        pcfRatio:
          type: number
          format: double
        grossMarginTTM:
          type: number
          format: double
        grossMarginMRQ:
          type: number
          format: double
        netProfitMarginTTM:
          type: number
          format: double
        netProfitMarginMRQ:
          type: number
          format: double
        operatingMarginTTM:
          type: number
          format: double
        operatingMarginMRQ:
          type: number
          format: double
        returnOnEquity:
          type: number
          format: double
        returnOnAssets:
          type: number
          format: double
        returnOnInvestment:
          type: number
          format: double
        quickRatio:
          type: number
          format: double
        currentRatio:
          type: number
          format: double
        interestCoverage:
          type: number
          format: double
        totalDebtToCapital:
          type: number
          format: double
        ltDebtToEquity:
          type: number
          format: double
        totalDebtToEquity:
          type: number
          format: double
        epsTTM:
          type: number
          format: double
        epsChangePercentTTM:
          type: number
          format: double
        epsChangeYear:
          type: number
          format: double
        epsChange:
          type: number
          format: double
        revChangeYear:
          type: number
          format: double
        revChangeTTM:
          type: number
          format: double
        revChangeIn:
          type: number
          format: double
        sharesOutstanding:
          type: number
          format: double
        marketCapFloat:
          type: number
          format: double
        marketCap:
          type: number
          format: double
        bookValuePerShare:
          type: number
          format: double
        shortIntToFloat:
          type: number
          format: double
        shortIntDayToCover:
          type: number
          format: double
        divGrowthRate3Year:
          type: number
          format: double
        dividendPayAmount:
          type: number
          format: double
        dividendPayDate:
          type: string
        beta:
          type: number
          format: double
        vol1DayAvg:
          type: number
          format: double
        vol10DayAvg:
          type: number
          format: double
        vol3MonthAvg:
          type: number
          format: double
    Fundamental:
      type: object
      properties:
        cusip:
          type: string
        symbol:
          type: string
        description:
          type: string
        exchange:
          type: string
        assetType:
          type: string
          enum:
          - EQUITY
          - ETF
          - MUTUAL_FUND
          - UNKNOWN
        fundamental:
          $ref: '#/components/schemas/Fundamental_fundamental'
    Instrument:
      type: object
      properties:
        cusip:
          type: string
        symbol:
          type: string
        description:
          type: string
        exchange:
          type: string
        assetType:
          type: string
          enum:
          - EQUITY
          - ETF
          - FOREX
          - FUTURE
          - FUTURE_OPTION
          - INDEX
          - INDICATOR
          - MUTUAL_FUND
          - OPTION
          - UNKNOWN
    inline_response_200:
      oneOf:
      - $ref: '#/components/schemas/Bond'
      - $ref: '#/components/schemas/Fundamental'
      - $ref: '#/components/schemas/FundamentalData'
      - $ref: '#/components/schemas/Instrument'
    CandleList_candles:
      type: object
      properties:
        close:
          type: number
          description: Close
          format: double
        datetime:
          type: integer
          description: DateTime
          format: int64
        high:
          type: number
          description: High
          format: double
        low:
          type: number
          description: Low
          format: double
        open:
          type: number
          description: Open
          format: double
        volume:
          type: number
          description: Volume
          format: double
      example:
        volume: 2.3021358869347654518833223846741020679473876953125
        datetime: 6
        high: 1.46581298050294517310021547018550336360931396484375
        low: 5.962133916683182377482808078639209270477294921875
        close: 0.80082819046101150206595775671303272247314453125
        open: 5.63737665663332876420099637471139430999755859375
    Fundamental_fundamental:
      properties:
        schema:
          $ref: '#/components/schemas/FundamentalData'
  examples:
    bondObject:
      value:
        bondPrice: 11
        cusip: christopherqueen
        symbol: cdq
        descriptions: Chris Queen Madeup Bond
        exchange: CDQ
        assetType: BOND
    instrumentObject:
      value:
        cusip: 66987E206
        symbol: NG
        description: Novagold Resources Inc.
        exchange: AMEX
        assetType: EQUITY
    fundamentalDataObject:
      value:
        symbol: NG
        high52: 12.845
        low52: 4.65
        dividendAmount: 0
        dividendYield: 0
        peRatio: 0
        pegRatio: 0
        pbRatio: 21.99646
        prRatio: 0
        pcfRatio: 0
        grossMarginTTM: 0
        grossMarginMRQ: 0
        netProfitMarginTTM: 0
        netProfitMarginMRQ: 0
        operatingMarginTTM: 0
        operatingMarginMRQ: 0
        returnOnEquity: 0
        returnOnAssets: 0
        returnOnInvestment: 0
        quickRatio: 0
        currentRatio: 79.54602
        interestCoverage: 0,
        totalDebtToCapital: 44.61743
        ltDebtToEquity: 80.56223
        totalDebtToEquity: 80.56223
        epsTTM: 0
        epsChangePercentTTM: 7.09258
        epsChangeYear: 0
        epsChange: 0
        revChangeYear: 0
        revChangeTTM: 0
        revChangeIn: 0
        sharesOutstanding: 328671632
        marketCapFloat: 239.4534
        marketCap: 2855.913
        bookValuePerShare: 0
        shortIntToFloat: 0
        shortIntDayToCover: 0
        divGrowthRate3Year: 0
        dividendPayAmount: 0
        dividendPayDate: 0
        beta: 0.51493
        vol1DayAvg: 3357300
        vol10DayAvg: 3357303
        vol3MonthAvg: 77925210
    fundamentalObject:
      value:
        NG:
          fundamental:
            symbol: NG
            high52: 12.845
            low52: 4.65
            dividendAmount: 0
            dividendYield: 0
            peRatio: 0
            pegRatio: 0
            pbRatio: 21.99646
            prRatio: 0
            pcfRatio: 0
            grossMarginTTM: 0
            grossMarginMRQ: 0
            netProfitMarginTTM: 0
            netProfitMarginMRQ: 0
            operatingMarginTTM: 0
            operatingMarginMRQ: 0
            returnOnEquity: 0
            returnOnAssets: 0
            returnOnInvestment: 0
            quickRatio: 0
            currentRatio: 79.54602
            interestCoverage: 0,
            totalDebtToCapital: 44.61743
            ltDebtToEquity: 80.56223
            totalDebtToEquity: 80.56223
            epsTTM: 0
            epsChangePercentTTM: 7.09258
            epsChangeYear: 0
            epsChange: 0
            revChangeYear: 0
            revChangeTTM: 0
            revChangeIn: 0
            sharesOutstanding: 328671632
            marketCapFloat: 239.4534
            marketCap: 2855.913
            bookValuePerShare: 0
            shortIntToFloat: 0
            shortIntDayToCover: 0
            divGrowthRate3Year: 0
            dividendPayAmount: 0
            dividendPayDate: 0
            beta: 0.51493
            vol1DayAvg: 3357300
            vol10DayAvg: 3357303
            vol3MonthAvg: 77925210'
          cusip: 66987E206
          symbol: NG
          description: Novagold Resources Inc.
          exchange: AMEX
          assetType: EQUITY
  securitySchemes:
    application:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.tdameritrade.com/auth?response_type=code&redirect_uri=http%3A%2F%2Flocalhost&client_id=YHJUQFCHRMJ7XODGVGGPINB05SCG2H45%40AMER.OAUTHAP
          tokenUrl: /oauth2/token
          scopes: {}
    bearerAuth:
      type: http
      scheme: bearer
